CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "CategoryContents" (
    "CategoryContentId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Slug" character varying(250) NOT NULL,
    "Description" character varying(500),
    "IconUrl" text,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CategoryContents" PRIMARY KEY ("CategoryContentId")
);

CREATE TABLE "Chests" (
    "ChestId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(150) NOT NULL,
    "Description" text,
    "Type" text NOT NULL,
    "GoldMinReward" integer NOT NULL,
    "GoldMaxReward" integer NOT NULL,
    "ExperienceReward" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Chests" PRIMARY KEY ("ChestId")
);

CREATE TABLE "GachaBanners" (
    "GachaBannerId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(150) NOT NULL,
    "Type" text NOT NULL,
    "PullCost" integer NOT NULL,
    "PityLimit" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "StartAt" timestamp with time zone NOT NULL,
    "EndAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_GachaBanners" PRIMARY KEY ("GachaBannerId")
);

CREATE TABLE "GameAnnouncements" (
    "GameAnnouncementId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "Content" text NOT NULL,
    "Type" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "StartsAt" timestamp with time zone NOT NULL,
    "EndsAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_GameAnnouncements" PRIMARY KEY ("GameAnnouncementId")
);

CREATE TABLE "Items" (
    "ItemId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(150) NOT NULL,
    "Description" character varying(1000),
    "Type" text NOT NULL,
    "Rarity" text NOT NULL,
    "Slot" text NOT NULL,
    "BaseValue" numeric NOT NULL,
    "MaxStack" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "IconUrl" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Items" PRIMARY KEY ("ItemId")
);

CREATE TABLE "Monsters" (
    "MonsterId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(150) NOT NULL,
    "Type" text NOT NULL,
    "Description" text NOT NULL,
    "Level" integer NOT NULL,
    "MaxHp" integer NOT NULL,
    "Atk" integer NOT NULL,
    "Def" integer NOT NULL,
    "MoveSpeed" integer NOT NULL,
    "AttackSpeed" integer NOT NULL,
    "CritRate" integer NOT NULL,
    "CritDamage" integer NOT NULL,
    "ExperienceReward" integer NOT NULL,
    "GoldReward" numeric NOT NULL,
    "ImageUrl" text,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Monsters" PRIMARY KEY ("MonsterId")
);

CREATE TABLE "NPCs" (
    "NPCId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(150) NOT NULL,
    "Description" text,
    "Type" text NOT NULL,
    "MapName" character varying(100) NOT NULL,
    "PositionX" double precision NOT NULL,
    "PositionY" double precision NOT NULL,
    "InteractionRadius" real NOT NULL,
    "IconUrl" text,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_NPCs" PRIMARY KEY ("NPCId")
);

CREATE TABLE "Roles" (
    "RoleId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("RoleId")
);

CREATE TABLE "Skills" (
    "SkillId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(150) NOT NULL,
    "Description" text,
    "Type" text NOT NULL,
    "DamageType" text NOT NULL,
    "TargetType" text NOT NULL,
    "ClassRequirement" text NOT NULL,
    "CooldownSeconds" integer NOT NULL,
    "BaseDamage" integer NOT NULL,
    "DamagePerLevel" integer NOT NULL,
    "DamageGrowthPercent" double precision NOT NULL,
    "UnlockLevel" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Skills" PRIMARY KEY ("SkillId")
);

CREATE TABLE "Skins" (
    "SkinId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(150) NOT NULL,
    "Description" text,
    "Type" text NOT NULL,
    "Rarity" text NOT NULL,
    "IconUrl" text,
    "PreviewUrl" text,
    "Currency" text NOT NULL,
    "Price" numeric NOT NULL,
    "IsForSale" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Skins" PRIMARY KEY ("SkinId")
);

CREATE TABLE "DungeonConfigs" (
    "DungeonConfigId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(150) NOT NULL,
    "Description" character varying(500),
    "ImageUrl" text,
    "Type" text NOT NULL,
    "LevelRequirement" integer NOT NULL,
    "MaxMembers" integer NOT NULL,
    "Difficulty" integer NOT NULL,
    "RecommendedPower" integer NOT NULL,
    "ChestId" integer,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_DungeonConfigs" PRIMARY KEY ("DungeonConfigId"),
    CONSTRAINT "FK_DungeonConfigs_Chests_ChestId" FOREIGN KEY ("ChestId") REFERENCES "Chests" ("ChestId")
);

CREATE TABLE "Achievements" (
    "AchievementId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(150) NOT NULL,
    "Description" text,
    "Type" text NOT NULL,
    "IconUrl" text,
    "RequiredValue" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "RewardItemId" integer,
    "RewardQuantity" integer NOT NULL,
    "RewardGold" numeric NOT NULL,
    "RewardGem" integer NOT NULL,
    "Point" integer NOT NULL,
    CONSTRAINT "PK_Achievements" PRIMARY KEY ("AchievementId"),
    CONSTRAINT "FK_Achievements_Items_RewardItemId" FOREIGN KEY ("RewardItemId") REFERENCES "Items" ("ItemId")
);

CREATE TABLE "ChestItems" (
    "ChestItemId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ChestId" integer NOT NULL,
    "ItemId" integer NOT NULL,
    "QuantityMin" integer NOT NULL,
    "QuantityMax" integer NOT NULL,
    "DropRate" numeric NOT NULL,
    "IsGuaranteed" boolean NOT NULL,
    CONSTRAINT "PK_ChestItems" PRIMARY KEY ("ChestItemId"),
    CONSTRAINT "FK_ChestItems_Chests_ChestId" FOREIGN KEY ("ChestId") REFERENCES "Chests" ("ChestId") ON DELETE CASCADE,
    CONSTRAINT "FK_ChestItems_Items_ItemId" FOREIGN KEY ("ItemId") REFERENCES "Items" ("ItemId") ON DELETE CASCADE
);

CREATE TABLE "DailyLoginRewards" (
    "DailyLoginRewardId" integer GENERATED BY DEFAULT AS IDENTITY,
    "DayNumber" integer NOT NULL,
    "RewardType" text NOT NULL,
    "RewardValue" numeric NOT NULL,
    "RewardItemId" integer,
    "RewardItemQuantity" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_DailyLoginRewards" PRIMARY KEY ("DailyLoginRewardId"),
    CONSTRAINT "FK_DailyLoginRewards_Items_RewardItemId" FOREIGN KEY ("RewardItemId") REFERENCES "Items" ("ItemId")
);

CREATE TABLE "EquipmentStats" (
    "EquipmentStatsId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ItemId" integer NOT NULL,
    "BaseHp" integer NOT NULL,
    "BaseAtk" integer NOT NULL,
    "BaseDef" integer NOT NULL,
    "BonusHp" integer NOT NULL,
    "BonusAtk" integer NOT NULL,
    "BonusDef" integer NOT NULL,
    "BonusMoveSpeed" integer NOT NULL,
    "BonusAttackSpeed" integer NOT NULL,
    "BonusCritRate" integer NOT NULL,
    "BonusCritDamage" integer NOT NULL,
    "BonusDamageBonus" integer NOT NULL,
    CONSTRAINT "PK_EquipmentStats" PRIMARY KEY ("EquipmentStatsId"),
    CONSTRAINT "FK_EquipmentStats_Items_ItemId" FOREIGN KEY ("ItemId") REFERENCES "Items" ("ItemId") ON DELETE CASCADE
);

CREATE TABLE "GachaBannerItems" (
    "GachaBannerItemId" integer GENERATED BY DEFAULT AS IDENTITY,
    "GachaBannerId" integer NOT NULL,
    "ItemId" integer NOT NULL,
    "DropRate" numeric NOT NULL,
    "IsFeatured" boolean NOT NULL,
    CONSTRAINT "PK_GachaBannerItems" PRIMARY KEY ("GachaBannerItemId"),
    CONSTRAINT "FK_GachaBannerItems_GachaBanners_GachaBannerId" FOREIGN KEY ("GachaBannerId") REFERENCES "GachaBanners" ("GachaBannerId") ON DELETE CASCADE,
    CONSTRAINT "FK_GachaBannerItems_Items_ItemId" FOREIGN KEY ("ItemId") REFERENCES "Items" ("ItemId") ON DELETE CASCADE
);

CREATE TABLE "Quests" (
    "QuestId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "Description" text,
    "Type" text NOT NULL,
    "DefaultStatus" text NOT NULL,
    "MapName" character varying(100) NOT NULL,
    "RegionName" character varying(100),
    "ObjectiveType" text NOT NULL,
    "ObjectiveTarget" text,
    "ObjectiveLocation" text,
    "QuestGiverName" text,
    "RequiredLevel" integer NOT NULL,
    "TargetAmount" integer NOT NULL,
    "RewardExperience" integer NOT NULL,
    "RewardGold" numeric NOT NULL,
    "RewardGems" numeric NOT NULL,
    "RewardItemId" integer,
    "RewardSkillId" integer,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Quests" PRIMARY KEY ("QuestId"),
    CONSTRAINT "FK_Quests_Items_RewardItemId" FOREIGN KEY ("RewardItemId") REFERENCES "Items" ("ItemId")
    ,CONSTRAINT "FK_Quests_Skills_RewardSkillId" FOREIGN KEY ("RewardSkillId") REFERENCES "Skills" ("SkillId")
);

CREATE TABLE "ShopItems" (
    "ShopItemId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ItemId" integer NOT NULL,
    "Currency" text NOT NULL,
    "Price" numeric NOT NULL,
    "Stock" integer NOT NULL,
    "DailyPurchaseLimit" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "AvailableFrom" timestamp with time zone,
    "AvailableTo" timestamp with time zone,
    CONSTRAINT "PK_ShopItems" PRIMARY KEY ("ShopItemId"),
    CONSTRAINT "FK_ShopItems_Items_ItemId" FOREIGN KEY ("ItemId") REFERENCES "Items" ("ItemId") ON DELETE CASCADE
);

CREATE TABLE "MonsterDrops" (
    "MonsterDropId" integer GENERATED BY DEFAULT AS IDENTITY,
    "MonsterId" integer NOT NULL,
    "ItemId" integer NOT NULL,
    "DropRate" double precision NOT NULL,
    "MinQuantity" integer NOT NULL,
    "MaxQuantity" integer NOT NULL,
    "IsGuaranteed" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_MonsterDrops" PRIMARY KEY ("MonsterDropId"),
    CONSTRAINT "FK_MonsterDrops_Items_ItemId" FOREIGN KEY ("ItemId") REFERENCES "Items" ("ItemId") ON DELETE CASCADE,
    CONSTRAINT "FK_MonsterDrops_Monsters_MonsterId" FOREIGN KEY ("MonsterId") REFERENCES "Monsters" ("MonsterId") ON DELETE CASCADE
);

CREATE TABLE "Accounts" (
    "AccountId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserName" text NOT NULL,
    "Email" text NOT NULL,
    "HashPassword" text NOT NULL,
    "RoleId" integer NOT NULL,
    "RefreshToken" text,
    "RefreshTokenExpiresAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "LastLogin" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Accounts" PRIMARY KEY ("AccountId"),
    CONSTRAINT "FK_Accounts_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("RoleId") ON DELETE CASCADE
);

CREATE TABLE "NPCDialogues" (
    "NPCDialogueId" integer GENERATED BY DEFAULT AS IDENTITY,
    "NPCId" integer NOT NULL,
    "Content" text NOT NULL,
    "ResponseType" text NOT NULL,
    "LinkedQuestId" integer,
    "LinkedShopItemId" integer,
    "DisplayOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_NPCDialogues" PRIMARY KEY ("NPCDialogueId"),
    CONSTRAINT "FK_NPCDialogues_NPCs_NPCId" FOREIGN KEY ("NPCId") REFERENCES "NPCs" ("NPCId") ON DELETE CASCADE,
    CONSTRAINT "FK_NPCDialogues_Quests_LinkedQuestId" FOREIGN KEY ("LinkedQuestId") REFERENCES "Quests" ("QuestId"),
    CONSTRAINT "FK_NPCDialogues_ShopItems_LinkedShopItemId" FOREIGN KEY ("LinkedShopItemId") REFERENCES "ShopItems" ("ShopItemId")
);

CREATE TABLE "Contents" (
    "ContentId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(250) NOT NULL,
    "Slug" character varying(250) NOT NULL,
    "Summary" text,
    "ThumbnailUrl" text,
    "CategoryContentId" integer,
    "IsPublished" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "PublishedAt" timestamp with time zone,
    "CreatedByAccountId" uuid NOT NULL,
    "CreatedByAccountAccountId" integer,
    CONSTRAINT "PK_Contents" PRIMARY KEY ("ContentId"),
    CONSTRAINT "FK_Contents_Accounts_CreatedByAccountAccountId" FOREIGN KEY ("CreatedByAccountAccountId") REFERENCES "Accounts" ("AccountId"),
    CONSTRAINT "FK_Contents_CategoryContents_CategoryContentId" FOREIGN KEY ("CategoryContentId") REFERENCES "CategoryContents" ("CategoryContentId")
);

CREATE TABLE "GameSettings" (
    "GameSettingId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Value" text,
    "Description" text,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedByAccountId" uuid,
    "CreatedByAccountAccountId" integer,
    "UpdatedByAccountId" uuid,
    "UpdatedByAccountAccountId" integer,
    CONSTRAINT "PK_GameSettings" PRIMARY KEY ("GameSettingId"),
    CONSTRAINT "FK_GameSettings_Accounts_CreatedByAccountAccountId" FOREIGN KEY ("CreatedByAccountAccountId") REFERENCES "Accounts" ("AccountId"),
    CONSTRAINT "FK_GameSettings_Accounts_UpdatedByAccountAccountId" FOREIGN KEY ("UpdatedByAccountAccountId") REFERENCES "Accounts" ("AccountId")
);

CREATE TABLE "PlayerProfiles" (
    "PlayerProfileId" integer GENERATED BY DEFAULT AS IDENTITY,
    "AccountId" integer NOT NULL,
    "DisplayName" character varying(100) NOT NULL,
    "AvatarUrl" text NOT NULL,
    "Class" text NOT NULL,
    "Level" integer NOT NULL,
    "ExperiencePoints" integer NOT NULL,
    "Gold" numeric NOT NULL,
    "Gems" numeric NOT NULL,
    "Energy" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "TotalDungeonClears" integer NOT NULL,
    "LastMapName" text NOT NULL,
    "PositionX" double precision NOT NULL,
    "PositionY" double precision NOT NULL,
    CONSTRAINT "PK_PlayerProfiles" PRIMARY KEY ("PlayerProfileId"),
    CONSTRAINT "FK_PlayerProfiles_Accounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES "Accounts" ("AccountId") ON DELETE CASCADE
);

CREATE TABLE "BlockContents" (
    "BlockContentId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ContentId" integer NOT NULL,
    "ContentData" text,
    "MediaUrl" text,
    "Caption" text,
    "BlockType" text NOT NULL,
    "SortOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_BlockContents" PRIMARY KEY ("BlockContentId"),
    CONSTRAINT "FK_BlockContents_Contents_ContentId" FOREIGN KEY ("ContentId") REFERENCES "Contents" ("ContentId") ON DELETE CASCADE
);

CREATE TABLE "ChatMessages" (
    "ChatMessageId" integer GENERATED BY DEFAULT AS IDENTITY,
    "SenderId" integer NOT NULL,
    "RecipientId" integer NOT NULL,
    "Content" character varying(500) NOT NULL,
    "IsReported" boolean NOT NULL,
    "IsHidden" boolean NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ChatMessages" PRIMARY KEY ("ChatMessageId"),
    CONSTRAINT "FK_ChatMessages_PlayerProfiles_RecipientId" FOREIGN KEY ("RecipientId") REFERENCES "PlayerProfiles" ("PlayerProfileId") ON DELETE CASCADE,
    CONSTRAINT "FK_ChatMessages_PlayerProfiles_SenderId" FOREIGN KEY ("SenderId") REFERENCES "PlayerProfiles" ("PlayerProfileId") ON DELETE CASCADE
);

CREATE TABLE "Friends" (
    "FriendId" integer GENERATED BY DEFAULT AS IDENTITY,
    "RequesterId" integer NOT NULL,
    "AddresseeId" integer NOT NULL,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "RespondedAt" timestamp with time zone,
    CONSTRAINT "PK_Friends" PRIMARY KEY ("FriendId"),
    CONSTRAINT "FK_Friends_PlayerProfiles_AddresseeId" FOREIGN KEY ("AddresseeId") REFERENCES "PlayerProfiles" ("PlayerProfileId") ON DELETE CASCADE,
    CONSTRAINT "FK_Friends_PlayerProfiles_RequesterId" FOREIGN KEY ("RequesterId") REFERENCES "PlayerProfiles" ("PlayerProfileId") ON DELETE CASCADE
);

CREATE TABLE "GachaPullHistories" (
    "GachaPullHistoryId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlayerProfileId" integer NOT NULL,
    "GachaBannerId" integer NOT NULL,
    "RewardItemId" integer NOT NULL,
    "PullCount" integer NOT NULL,
    "CostSpent" numeric NOT NULL,
    "PulledAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_GachaPullHistories" PRIMARY KEY ("GachaPullHistoryId"),
    CONSTRAINT "FK_GachaPullHistories_GachaBanners_GachaBannerId" FOREIGN KEY ("GachaBannerId") REFERENCES "GachaBanners" ("GachaBannerId") ON DELETE CASCADE,
    CONSTRAINT "FK_GachaPullHistories_Items_RewardItemId" FOREIGN KEY ("RewardItemId") REFERENCES "Items" ("ItemId") ON DELETE CASCADE,
    CONSTRAINT "FK_GachaPullHistories_PlayerProfiles_PlayerProfileId" FOREIGN KEY ("PlayerProfileId") REFERENCES "PlayerProfiles" ("PlayerProfileId") ON DELETE CASCADE
);

CREATE TABLE "Guilds" (
    "GuildId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" text,
    "IconUrl" text,
    "LeaderId" integer NOT NULL,
    "MaxMembers" integer NOT NULL,
    "Level" integer NOT NULL,
    "Experience" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Guilds" PRIMARY KEY ("GuildId"),
    CONSTRAINT "FK_Guilds_PlayerProfiles_LeaderId" FOREIGN KEY ("LeaderId") REFERENCES "PlayerProfiles" ("PlayerProfileId") ON DELETE CASCADE
);

CREATE TABLE "InventoryItems" (
    "InventoryItemId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlayerProfileId" integer NOT NULL,
    "ItemId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "IsEquipped" boolean NOT NULL,
    "IsSkin" boolean NOT NULL,
    "EquippedSlot" text,
    "EnhancementLevel" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_InventoryItems" PRIMARY KEY ("InventoryItemId"),
    CONSTRAINT "FK_InventoryItems_Items_ItemId" FOREIGN KEY ("ItemId") REFERENCES "Items" ("ItemId") ON DELETE CASCADE,
    CONSTRAINT "FK_InventoryItems_PlayerProfiles_PlayerProfileId" FOREIGN KEY ("PlayerProfileId") REFERENCES "PlayerProfiles" ("PlayerProfileId") ON DELETE CASCADE
);

CREATE TABLE "Mails" (
    "MailId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlayerProfileId" integer NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Content" text NOT NULL,
    "Type" text NOT NULL,
    "AttachedGold" numeric NOT NULL,
    "AttachedGems" numeric NOT NULL,
    "AttachedItemId" integer,
    "AttachedItemQuantity" integer NOT NULL,
    "IsRead" boolean NOT NULL,
    "IsClaimed" boolean NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,
    "ExpiredAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Mails" PRIMARY KEY ("MailId"),
    CONSTRAINT "FK_Mails_Items_AttachedItemId" FOREIGN KEY ("AttachedItemId") REFERENCES "Items" ("ItemId"),
    CONSTRAINT "FK_Mails_PlayerProfiles_PlayerProfileId" FOREIGN KEY ("PlayerProfileId") REFERENCES "PlayerProfiles" ("PlayerProfileId") ON DELETE CASCADE
);

CREATE TABLE "PlayerAchievements" (
    "PlayerAchievementId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlayerProfileId" integer NOT NULL,
    "AchievementId" integer NOT NULL,
    "Progress" integer NOT NULL,
    "IsCompleted" boolean NOT NULL,
    "CompletedAt" timestamp with time zone,
    "UnlockedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PlayerAchievements" PRIMARY KEY ("PlayerAchievementId"),
    CONSTRAINT "FK_PlayerAchievements_Achievements_AchievementId" FOREIGN KEY ("AchievementId") REFERENCES "Achievements" ("AchievementId") ON DELETE CASCADE,
    CONSTRAINT "FK_PlayerAchievements_PlayerProfiles_PlayerProfileId" FOREIGN KEY ("PlayerProfileId") REFERENCES "PlayerProfiles" ("PlayerProfileId") ON DELETE CASCADE
);

CREATE TABLE "PlayerAnnouncements" (
    "PlayerAnnouncementId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlayerProfileId" integer NOT NULL,
    "GameAnnouncementId" integer NOT NULL,
    "IsRead" boolean NOT NULL,
    "ReadAt" timestamp with time zone,
    CONSTRAINT "PK_PlayerAnnouncements" PRIMARY KEY ("PlayerAnnouncementId"),
    CONSTRAINT "FK_PlayerAnnouncements_GameAnnouncements_GameAnnouncementId" FOREIGN KEY ("GameAnnouncementId") REFERENCES "GameAnnouncements" ("GameAnnouncementId") ON DELETE CASCADE,
    CONSTRAINT "FK_PlayerAnnouncements_PlayerProfiles_PlayerProfileId" FOREIGN KEY ("PlayerProfileId") REFERENCES "PlayerProfiles" ("PlayerProfileId") ON DELETE CASCADE
);

CREATE TABLE "PlayerChests" (
    "PlayerChestId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlayerProfileId" integer NOT NULL,
    "ChestId" integer NOT NULL,
    "IsOpened" boolean NOT NULL,
    "ReceivedAt" timestamp with time zone NOT NULL,
    "OpenedAt" timestamp with time zone,
    CONSTRAINT "PK_PlayerChests" PRIMARY KEY ("PlayerChestId"),
    CONSTRAINT "FK_PlayerChests_Chests_ChestId" FOREIGN KEY ("ChestId") REFERENCES "Chests" ("ChestId") ON DELETE CASCADE,
    CONSTRAINT "FK_PlayerChests_PlayerProfiles_PlayerProfileId" FOREIGN KEY ("PlayerProfileId") REFERENCES "PlayerProfiles" ("PlayerProfileId") ON DELETE CASCADE
);

CREATE TABLE "PlayerCurrencyLogs" (
    "PlayerCurrencyLogId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlayerProfileId" integer NOT NULL,
    "Currency" text NOT NULL,
    "Type" text NOT NULL,
    "Amount" numeric NOT NULL,
    "BalanceAfter" numeric NOT NULL,
    "Note" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PlayerCurrencyLogs" PRIMARY KEY ("PlayerCurrencyLogId"),
    CONSTRAINT "FK_PlayerCurrencyLogs_PlayerProfiles_PlayerProfileId" FOREIGN KEY ("PlayerProfileId") REFERENCES "PlayerProfiles" ("PlayerProfileId") ON DELETE CASCADE
);

CREATE TABLE "PlayerDailyLogins" (
    "PlayerDailyLoginId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlayerProfileId" integer NOT NULL,
    "CurrentStreak" integer NOT NULL,
    "TotalDaysClaimed" integer NOT NULL,
    "LastClaimedAt" timestamp with time zone,
    "IsClaimedToday" boolean NOT NULL,
    CONSTRAINT "PK_PlayerDailyLogins" PRIMARY KEY ("PlayerDailyLoginId"),
    CONSTRAINT "FK_PlayerDailyLogins_PlayerProfiles_PlayerProfileId" FOREIGN KEY ("PlayerProfileId") REFERENCES "PlayerProfiles" ("PlayerProfileId") ON DELETE CASCADE
);

CREATE TABLE "PlayerQuests" (
    "PlayerQuestId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlayerProfileId" integer NOT NULL,
    "QuestId" integer NOT NULL,
    "Status" text NOT NULL,
    "Progress" integer NOT NULL,
    "TargetValue" integer NOT NULL,
    "AcceptedAt" timestamp with time zone NOT NULL,
    "CompletedAt" timestamp with time zone,
    "ClaimedAt" timestamp with time zone,
    CONSTRAINT "PK_PlayerQuests" PRIMARY KEY ("PlayerQuestId"),
    CONSTRAINT "FK_PlayerQuests_PlayerProfiles_PlayerProfileId" FOREIGN KEY ("PlayerProfileId") REFERENCES "PlayerProfiles" ("PlayerProfileId") ON DELETE CASCADE,
    CONSTRAINT "FK_PlayerQuests_Quests_QuestId" FOREIGN KEY ("QuestId") REFERENCES "Quests" ("QuestId") ON DELETE CASCADE
);

CREATE TABLE "PlayerSkills" (
    "PlayerSkillId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlayerProfileId" integer NOT NULL,
    "SkillId" integer NOT NULL,
    "Level" integer NOT NULL,
    "Experience" integer NOT NULL,
    "IsEquipped" boolean NOT NULL,
    "UnlockedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PlayerSkills" PRIMARY KEY ("PlayerSkillId"),
    CONSTRAINT "FK_PlayerSkills_PlayerProfiles_PlayerProfileId" FOREIGN KEY ("PlayerProfileId") REFERENCES "PlayerProfiles" ("PlayerProfileId") ON DELETE CASCADE,
    CONSTRAINT "FK_PlayerSkills_Skills_SkillId" FOREIGN KEY ("SkillId") REFERENCES "Skills" ("SkillId") ON DELETE CASCADE
);

CREATE TABLE "PlayerSkins" (
    "PlayerSkinId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlayerProfileId" integer NOT NULL,
    "SkinId" integer NOT NULL,
    "IsEquipped" boolean NOT NULL,
    "UnlockedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PlayerSkins" PRIMARY KEY ("PlayerSkinId"),
    CONSTRAINT "FK_PlayerSkins_PlayerProfiles_PlayerProfileId" FOREIGN KEY ("PlayerProfileId") REFERENCES "PlayerProfiles" ("PlayerProfileId") ON DELETE CASCADE,
    CONSTRAINT "FK_PlayerSkins_Skins_SkinId" FOREIGN KEY ("SkinId") REFERENCES "Skins" ("SkinId") ON DELETE CASCADE
);

CREATE TABLE "PlayerStats" (
    "PlayerStatId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlayerProfileId" integer NOT NULL,
    "CurrentHp" integer NOT NULL,
    "MaxHp" integer NOT NULL,
    "Atk" integer NOT NULL,
    "Def" integer NOT NULL,
    "MoveSpeed" integer NOT NULL,
    "AttackSpeed" integer NOT NULL,
    "CritRate" integer NOT NULL,
    "CritDamage" integer NOT NULL,
    "DamageBonus" integer NOT NULL,
    "SkillPoints" integer NOT NULL,
    "TotalWins" integer NOT NULL,
    "TotalLosses" integer NOT NULL,
    "TotalKills" integer NOT NULL,
    "TotalDeaths" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_PlayerStats" PRIMARY KEY ("PlayerStatId"),
    CONSTRAINT "FK_PlayerStats_PlayerProfiles_PlayerProfileId" FOREIGN KEY ("PlayerProfileId") REFERENCES "PlayerProfiles" ("PlayerProfileId") ON DELETE CASCADE
);

CREATE TABLE "PlayerStatsSnapshots" (
    "PlayerStatsSnapshotId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlayerProfileId" integer NOT NULL,
    "MaxHp" integer NOT NULL,
    "Atk" integer NOT NULL,
    "Def" integer NOT NULL,
    "MoveSpeed" integer NOT NULL,
    "AttackSpeed" integer NOT NULL,
    "CritRate" integer NOT NULL,
    "CritDamage" integer NOT NULL,
    "DamageBonus" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "RowVersion" bytea,
    CONSTRAINT "PK_PlayerStatsSnapshots" PRIMARY KEY ("PlayerStatsSnapshotId"),
    CONSTRAINT "FK_PlayerStatsSnapshots_PlayerProfiles_PlayerProfileId" FOREIGN KEY ("PlayerProfileId") REFERENCES "PlayerProfiles" ("PlayerProfileId") ON DELETE CASCADE
);

CREATE TABLE "PurchaseHistories" (
    "PurchaseHistoryId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlayerProfileId" integer NOT NULL,
    "ShopItemId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "TotalPrice" numeric NOT NULL,
    "PurchasedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PurchaseHistories" PRIMARY KEY ("PurchaseHistoryId"),
    CONSTRAINT "FK_PurchaseHistories_PlayerProfiles_PlayerProfileId" FOREIGN KEY ("PlayerProfileId") REFERENCES "PlayerProfiles" ("PlayerProfileId") ON DELETE CASCADE,
    CONSTRAINT "FK_PurchaseHistories_ShopItems_ShopItemId" FOREIGN KEY ("ShopItemId") REFERENCES "ShopItems" ("ShopItemId") ON DELETE CASCADE
);

CREATE TABLE "GuildInvitations" (
    "GuildInvitationId" integer GENERATED BY DEFAULT AS IDENTITY,
    "GuildId" integer NOT NULL,
    "InviterId" integer NOT NULL,
    "InviteeId" integer NOT NULL,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "RespondedAt" timestamp with time zone,
    CONSTRAINT "PK_GuildInvitations" PRIMARY KEY ("GuildInvitationId"),
    CONSTRAINT "FK_GuildInvitations_Guilds_GuildId" FOREIGN KEY ("GuildId") REFERENCES "Guilds" ("GuildId") ON DELETE CASCADE,
    CONSTRAINT "FK_GuildInvitations_PlayerProfiles_InviteeId" FOREIGN KEY ("InviteeId") REFERENCES "PlayerProfiles" ("PlayerProfileId") ON DELETE CASCADE,
    CONSTRAINT "FK_GuildInvitations_PlayerProfiles_InviterId" FOREIGN KEY ("InviterId") REFERENCES "PlayerProfiles" ("PlayerProfileId") ON DELETE CASCADE
);

CREATE TABLE "GuildMembers" (
    "GuildMemberId" integer GENERATED BY DEFAULT AS IDENTITY,
    "GuildId" integer NOT NULL,
    "PlayerProfileId" integer NOT NULL,
    "Role" text NOT NULL,
    "Contribution" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "JoinedAt" timestamp with time zone NOT NULL,
    "LeftAt" timestamp with time zone,
    CONSTRAINT "PK_GuildMembers" PRIMARY KEY ("GuildMemberId"),
    CONSTRAINT "FK_GuildMembers_Guilds_GuildId" FOREIGN KEY ("GuildId") REFERENCES "Guilds" ("GuildId") ON DELETE CASCADE,
    CONSTRAINT "FK_GuildMembers_PlayerProfiles_PlayerProfileId" FOREIGN KEY ("PlayerProfileId") REFERENCES "PlayerProfiles" ("PlayerProfileId") ON DELETE CASCADE
);

INSERT INTO "Roles" ("RoleId", "Name")
VALUES (1, 'Player');
INSERT INTO "Roles" ("RoleId", "Name")
VALUES (2, 'Admin');
INSERT INTO "Roles" ("RoleId", "Name")
VALUES (3, 'SuperAdmin');

CREATE INDEX "IX_Accounts_RoleId" ON "Accounts" ("RoleId");

CREATE INDEX "IX_Achievements_RewardItemId" ON "Achievements" ("RewardItemId");

CREATE INDEX "IX_BlockContents_ContentId" ON "BlockContents" ("ContentId");

CREATE INDEX "IX_ChatMessages_RecipientId" ON "ChatMessages" ("RecipientId");

CREATE INDEX "IX_ChatMessages_SenderId" ON "ChatMessages" ("SenderId");

CREATE INDEX "IX_ChestItems_ChestId" ON "ChestItems" ("ChestId");

CREATE INDEX "IX_ChestItems_ItemId" ON "ChestItems" ("ItemId");

CREATE INDEX "IX_Contents_CategoryContentId" ON "Contents" ("CategoryContentId");

CREATE INDEX "IX_Contents_CreatedByAccountAccountId" ON "Contents" ("CreatedByAccountAccountId");

CREATE INDEX "IX_DailyLoginRewards_RewardItemId" ON "DailyLoginRewards" ("RewardItemId");

CREATE INDEX "IX_DungeonConfigs_ChestId" ON "DungeonConfigs" ("ChestId");

CREATE UNIQUE INDEX "IX_EquipmentStats_ItemId" ON "EquipmentStats" ("ItemId");

CREATE INDEX "IX_Friends_AddresseeId" ON "Friends" ("AddresseeId");

CREATE INDEX "IX_Friends_RequesterId" ON "Friends" ("RequesterId");

CREATE INDEX "IX_GachaBannerItems_GachaBannerId" ON "GachaBannerItems" ("GachaBannerId");

CREATE INDEX "IX_GachaBannerItems_ItemId" ON "GachaBannerItems" ("ItemId");

CREATE INDEX "IX_GachaPullHistories_GachaBannerId" ON "GachaPullHistories" ("GachaBannerId");

CREATE INDEX "IX_GachaPullHistories_PlayerProfileId" ON "GachaPullHistories" ("PlayerProfileId");

CREATE INDEX "IX_GachaPullHistories_RewardItemId" ON "GachaPullHistories" ("RewardItemId");

CREATE INDEX "IX_GameSettings_CreatedByAccountAccountId" ON "GameSettings" ("CreatedByAccountAccountId");

CREATE INDEX "IX_GameSettings_UpdatedByAccountAccountId" ON "GameSettings" ("UpdatedByAccountAccountId");

CREATE INDEX "IX_GuildInvitations_GuildId" ON "GuildInvitations" ("GuildId");

CREATE INDEX "IX_GuildInvitations_InviteeId" ON "GuildInvitations" ("InviteeId");

CREATE INDEX "IX_GuildInvitations_InviterId" ON "GuildInvitations" ("InviterId");

CREATE INDEX "IX_GuildMembers_GuildId" ON "GuildMembers" ("GuildId");

CREATE INDEX "IX_GuildMembers_PlayerProfileId" ON "GuildMembers" ("PlayerProfileId");

CREATE INDEX "IX_Guilds_LeaderId" ON "Guilds" ("LeaderId");

CREATE INDEX "IX_InventoryItems_ItemId" ON "InventoryItems" ("ItemId");

CREATE INDEX "IX_InventoryItems_PlayerProfileId" ON "InventoryItems" ("PlayerProfileId");

CREATE INDEX "IX_Mails_AttachedItemId" ON "Mails" ("AttachedItemId");

CREATE INDEX "IX_Mails_PlayerProfileId" ON "Mails" ("PlayerProfileId");

CREATE INDEX "IX_MonsterDrops_ItemId" ON "MonsterDrops" ("ItemId");

CREATE INDEX "IX_MonsterDrops_MonsterId" ON "MonsterDrops" ("MonsterId");

CREATE INDEX "IX_NPCDialogues_LinkedQuestId" ON "NPCDialogues" ("LinkedQuestId");

CREATE INDEX "IX_NPCDialogues_LinkedShopItemId" ON "NPCDialogues" ("LinkedShopItemId");

CREATE INDEX "IX_NPCDialogues_NPCId" ON "NPCDialogues" ("NPCId");

CREATE INDEX "IX_PlayerAchievements_AchievementId" ON "PlayerAchievements" ("AchievementId");

CREATE INDEX "IX_PlayerAchievements_PlayerProfileId" ON "PlayerAchievements" ("PlayerProfileId");

CREATE INDEX "IX_PlayerAnnouncements_GameAnnouncementId" ON "PlayerAnnouncements" ("GameAnnouncementId");

CREATE INDEX "IX_PlayerAnnouncements_PlayerProfileId" ON "PlayerAnnouncements" ("PlayerProfileId");

CREATE INDEX "IX_PlayerChests_ChestId" ON "PlayerChests" ("ChestId");

CREATE INDEX "IX_PlayerChests_PlayerProfileId" ON "PlayerChests" ("PlayerProfileId");

CREATE INDEX "IX_PlayerCurrencyLogs_PlayerProfileId" ON "PlayerCurrencyLogs" ("PlayerProfileId");

CREATE INDEX "IX_PlayerDailyLogins_PlayerProfileId" ON "PlayerDailyLogins" ("PlayerProfileId");

CREATE UNIQUE INDEX "IX_PlayerProfiles_AccountId" ON "PlayerProfiles" ("AccountId");

CREATE INDEX "IX_PlayerQuests_PlayerProfileId" ON "PlayerQuests" ("PlayerProfileId");

CREATE INDEX "IX_PlayerQuests_QuestId" ON "PlayerQuests" ("QuestId");

CREATE INDEX "IX_PlayerSkills_PlayerProfileId" ON "PlayerSkills" ("PlayerProfileId");

CREATE INDEX "IX_PlayerSkills_SkillId" ON "PlayerSkills" ("SkillId");

CREATE INDEX "IX_PlayerSkins_PlayerProfileId" ON "PlayerSkins" ("PlayerProfileId");

CREATE INDEX "IX_PlayerSkins_SkinId" ON "PlayerSkins" ("SkinId");

CREATE UNIQUE INDEX "IX_PlayerStats_PlayerProfileId" ON "PlayerStats" ("PlayerProfileId");

CREATE INDEX "IX_PlayerStatsSnapshots_PlayerProfileId" ON "PlayerStatsSnapshots" ("PlayerProfileId");

CREATE INDEX "IX_PurchaseHistories_PlayerProfileId" ON "PurchaseHistories" ("PlayerProfileId");

CREATE INDEX "IX_PurchaseHistories_ShopItemId" ON "PurchaseHistories" ("ShopItemId");

CREATE INDEX "IX_Quests_RewardItemId" ON "Quests" ("RewardItemId");

CREATE INDEX "IX_ShopItems_ItemId" ON "ShopItems" ("ItemId");

SELECT setval(
    pg_get_serial_sequence('"Roles"', 'RoleId'),
    GREATEST(
        (SELECT MAX("RoleId") FROM "Roles") + 1,
        nextval(pg_get_serial_sequence('"Roles"', 'RoleId'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260621132016_InitialCreate', '8.0.28');

COMMIT;

