using DAL.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(MysticJourneyDbContext))]
    [Migration("20260616100000_AddWorldQuestNpcMetadata")]
    public partial class AddWorldQuestNpcMetadata : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE ""Quests"" ADD COLUMN IF NOT EXISTS ""MapName"" character varying(100) NOT NULL DEFAULT 'ElfForest';
                ALTER TABLE ""Quests"" ADD COLUMN IF NOT EXISTS ""ObjectiveLocation"" text NULL;
                ALTER TABLE ""Quests"" ADD COLUMN IF NOT EXISTS ""ObjectiveTarget"" text NULL;
                ALTER TABLE ""Quests"" ADD COLUMN IF NOT EXISTS ""ObjectiveType"" text NOT NULL DEFAULT 'Explore';
                ALTER TABLE ""Quests"" ADD COLUMN IF NOT EXISTS ""QuestGiverName"" text NULL;
                ALTER TABLE ""Quests"" ADD COLUMN IF NOT EXISTS ""RegionName"" character varying(100) NULL;

                CREATE TABLE IF NOT EXISTS ""NPCs"" (
                    ""NPCId"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" character varying(150) NOT NULL,
                    ""Description"" text NULL,
                    ""Type"" text NOT NULL,
                    ""MapName"" character varying(100) NOT NULL,
                    ""PositionX"" double precision NOT NULL,
                    ""PositionY"" double precision NOT NULL,
                    ""InteractionRadius"" real NOT NULL,
                    ""IconUrl"" text NULL,
                    ""IsActive"" boolean NOT NULL,
                    CONSTRAINT ""PK_NPCs"" PRIMARY KEY (""NPCId"")
                );

                CREATE TABLE IF NOT EXISTS ""NPCDialogues"" (
                    ""NPCDialogueId"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""NPCId"" integer NOT NULL,
                    ""Content"" text NOT NULL,
                    ""ResponseType"" text NOT NULL,
                    ""LinkedQuestId"" integer NULL,
                    ""LinkedShopItemId"" integer NULL,
                    ""DisplayOrder"" integer NOT NULL,
                    ""IsActive"" boolean NOT NULL,
                    CONSTRAINT ""PK_NPCDialogues"" PRIMARY KEY (""NPCDialogueId"")
                );

                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_NPCDialogues_NPCs_NPCId') THEN
                        ALTER TABLE ""NPCDialogues"" ADD CONSTRAINT ""FK_NPCDialogues_NPCs_NPCId""
                            FOREIGN KEY (""NPCId"") REFERENCES ""NPCs"" (""NPCId"") ON DELETE CASCADE;
                    END IF;

                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_NPCDialogues_Quests_LinkedQuestId') THEN
                        ALTER TABLE ""NPCDialogues"" ADD CONSTRAINT ""FK_NPCDialogues_Quests_LinkedQuestId""
                            FOREIGN KEY (""LinkedQuestId"") REFERENCES ""Quests"" (""QuestId"") ON DELETE SET NULL;
                    END IF;

                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_NPCDialogues_ShopItems_LinkedShopItemId') THEN
                        ALTER TABLE ""NPCDialogues"" ADD CONSTRAINT ""FK_NPCDialogues_ShopItems_LinkedShopItemId""
                            FOREIGN KEY (""LinkedShopItemId"") REFERENCES ""ShopItems"" (""ShopItemId"") ON DELETE SET NULL;
                    END IF;
                END $$;

                CREATE INDEX IF NOT EXISTS ""IX_Quests_MapName"" ON ""Quests"" (""MapName"");
                CREATE INDEX IF NOT EXISTS ""IX_NPCs_MapName"" ON ""NPCs"" (""MapName"");
                CREATE INDEX IF NOT EXISTS ""IX_NPCDialogues_LinkedQuestId"" ON ""NPCDialogues"" (""LinkedQuestId"");
                CREATE INDEX IF NOT EXISTS ""IX_NPCDialogues_LinkedShopItemId"" ON ""NPCDialogues"" (""LinkedShopItemId"");
                CREATE INDEX IF NOT EXISTS ""IX_NPCDialogues_NPCId"" ON ""NPCDialogues"" (""NPCId"");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP INDEX IF EXISTS ""IX_NPCDialogues_NPCId"";
                DROP INDEX IF EXISTS ""IX_NPCDialogues_LinkedShopItemId"";
                DROP INDEX IF EXISTS ""IX_NPCDialogues_LinkedQuestId"";
                DROP INDEX IF EXISTS ""IX_NPCs_MapName"";
                DROP INDEX IF EXISTS ""IX_Quests_MapName"";

                DROP TABLE IF EXISTS ""NPCDialogues"";
                DROP TABLE IF EXISTS ""NPCs"";

                ALTER TABLE ""Quests"" DROP COLUMN IF EXISTS ""MapName"";
                ALTER TABLE ""Quests"" DROP COLUMN IF EXISTS ""ObjectiveLocation"";
                ALTER TABLE ""Quests"" DROP COLUMN IF EXISTS ""ObjectiveTarget"";
                ALTER TABLE ""Quests"" DROP COLUMN IF EXISTS ""ObjectiveType"";
                ALTER TABLE ""Quests"" DROP COLUMN IF EXISTS ""QuestGiverName"";
                ALTER TABLE ""Quests"" DROP COLUMN IF EXISTS ""RegionName"";
                """);
        }
    }
}