-- Migration: AddMonsterSpawnsAndDiscovery
-- Chạy script này trên PostgreSQL nếu chưa dùng `dotnet ef database update`.

ALTER TABLE "Quests" ADD COLUMN IF NOT EXISTS "BossMonsterId" integer NULL;

CREATE TABLE IF NOT EXISTS "Dungeons" (
    "DungeonId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" character varying(200) NOT NULL,
    "Description" text NULL,
    "IsRepeatable" boolean NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS "MonsterSpawns" (
    "MonsterSpawnId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MonsterId" integer NOT NULL,
    "MapName" character varying(100) NOT NULL,
    "RegionName" character varying(100) NULL,
    "Location" text NULL,
    "SpawnCount" integer NOT NULL DEFAULT 1,
    "RespawnSeconds" integer NOT NULL DEFAULT 60,
    "DungeonId" integer NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "FK_MonsterSpawns_Monsters_MonsterId"
        FOREIGN KEY ("MonsterId") REFERENCES "Monsters" ("MonsterId") ON DELETE CASCADE,
    CONSTRAINT "FK_MonsterSpawns_Dungeons_DungeonId"
        FOREIGN KEY ("DungeonId") REFERENCES "Dungeons" ("DungeonId") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "PlayerMonsterDiscoveries" (
    "PlayerMonsterDiscoveryId" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PlayerProfileId" integer NOT NULL,
    "MonsterId" integer NOT NULL,
    "IsDiscovered" boolean NOT NULL DEFAULT FALSE,
    "DiscoveredAt" timestamp with time zone NULL,
    "TimesDefeated" integer NOT NULL DEFAULT 0,
    CONSTRAINT "FK_PlayerMonsterDiscoveries_PlayerProfiles_PlayerProfileId"
        FOREIGN KEY ("PlayerProfileId") REFERENCES "PlayerProfiles" ("PlayerProfileId") ON DELETE CASCADE,
    CONSTRAINT "FK_PlayerMonsterDiscoveries_Monsters_MonsterId"
        FOREIGN KEY ("MonsterId") REFERENCES "Monsters" ("MonsterId") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_PlayerMonsterDiscoveries_PlayerProfileId_MonsterId"
    ON "PlayerMonsterDiscoveries" ("PlayerProfileId", "MonsterId");

CREATE INDEX IF NOT EXISTS "IX_MonsterSpawns_MonsterId"
    ON "MonsterSpawns" ("MonsterId");

CREATE INDEX IF NOT EXISTS "IX_MonsterSpawns_DungeonId"
    ON "MonsterSpawns" ("DungeonId");

CREATE INDEX IF NOT EXISTS "IX_Quests_BossMonsterId"
    ON "Quests" ("BossMonsterId");

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'FK_Quests_Monsters_BossMonsterId'
    ) THEN
        ALTER TABLE "Quests"
            ADD CONSTRAINT "FK_Quests_Monsters_BossMonsterId"
            FOREIGN KEY ("BossMonsterId") REFERENCES "Monsters" ("MonsterId") ON DELETE SET NULL;
    END IF;
END $$;
